<?php
$order = $this->getOrderData();
?>

<div class="card border-0 shadow-sm mb-4">
    <div class="card-header bg-white d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Recent Orders</h5>
        <a href="#" class="btn btn-sm btn-outline-primary">View All</a>
    </div>
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-hover mb-0">
                <thead class="table-light">
                    <tr>
                        <th>Order ID</th>
                        <th>Date</th>
                        <th>Items</th>
                        <th>Total</th>
                        <th>OrderNumber</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($order as $orderData):
                    ?>
                        <tr>
                            <td><?php echo $orderData->getOrderId(); ?></td>
                            <td><?php echo date("Y-m-d", strtotime($orderData->getCreatedAt())); ?></td>
                            <td>3 items</td>
                            <td><?php echo $orderData->getTotalAmount(); ?></td>
                            <td><?php echo $orderData->getOrderNumber(); ?></td>
                            <td><span class="badge bg-success">Delivered</span></td>
                            <td> <a href="<?php echo $this->getUrl('customer/dashboard/view') . "/?id=" . $orderData->getOrderId(); ?>"
                                    class="btn-success">
                                    View
                                </a></td>

                        </tr>
                    <?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </div>
</div>