<body>
    <div class="container">
        <div class="login-container">
            <h3 class="text-center mb-4 text-primary">eCommerce Login</h3>

            <?php if (!empty($error_message)) : ?>
                <div class="alert alert-danger"><?php echo $error_message; ?></div>
            <?php endif; ?>

            <form method="POST" action="loginPost">
                <div class="mb-3">
                    <label for="username" class="form-label">username</label>
                    <input type="text" name="username" class="form-control" required>
                </div>

                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" name="password" class="form-control" required>
                </div>
                <div class="mb-3">

                    <button type="submit" class="btn btn-primary w-100">Login</button>
                </div>
            </form>

            <p class="text-center mt-3">
                Don't have an account? <a href="register.php">Register</a>
            </p>
        </div>
    </div>

</body>