<div style="height:90vh">
    <div class="container d-flex justify-content-center align-items-center h-100">
        <div class="card p-4 shadow" style="width: 400px;">
            <h3 class="text-center mb-3">Customer Login</h3>
            <form id="login-form" method="POST" action="<?php echo $this->getUrl("*/*/loginPost") ?>">
                <div class="mb-3">
                    <label class="form-label" for="loginemail">Email Address</label>
                    <input type="email" class="form-control" name="login[email]" required>
                </div>
                <div class="mb-3">
                    <label class="form-label">Password</label>
                    <input type="password" class="form-control" name="login[password]" required>
                </div>
                <button type="submit" class="btn btn-primary w-100">Login</button>
            </form>
        </div>
    </div>
</div>