<?php $customer = $this->getCustomer(); ?>
<?php $address = $this->getAddress(); ?>
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-header bg-light text-dark">
                    <h3 class="mb-0">Create an Account</h3>
                </div>
                <div class="card-body">
                    <form method="POST" action="<?php echo $this->getUrl('customer/account/registerPost') ?>">
                        <div class="row mb-3">
                            <div class="col-md-6">
                                <label for="firstName" class="form-label">First Name</label>
                                <input type="text" class="form-control" id="firstName" name="customer[first_name]"
                                    value="<?php echo htmlspecialchars($customer->getFirstName(), ENT_QUOTES); ?>"
                                    required>
                            </div>
                            <div class="col-md-6">
                                <label for="lastName" class="form-label">Last Name</label>
                                <input type="text" class="form-control" id="lastName" name="customer[last_name]"
                                    value="<?php echo htmlspecialchars($customer->getLastName(), ENT_QUOTES); ?>"
                                    required>
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="email" class="form-label">Email Address</label>
                            <input type="email" class="form-control" id="email" name="customer[email]"
                                value="<?php echo htmlspecialchars($customer->getEmail(), ENT_QUOTES); ?>" required>
                        </div>

                        <div class="mb-3">
                            <label for="phone" class="form-label">Phone Number</label>
                            <input type="tel" class="form-control" id="phone" name="customer[phone]"
                                value="<?php echo htmlspecialchars($customer->getPhone(), ENT_QUOTES); ?>" required>
                        </div>
                        <div class="mb-3">
                            <label for="user_name" class="form-label">User Name</label>
                            <input type="tel" class="form-control" id="user_name" name="customer[user_name]"
                                value="<?php echo htmlspecialchars($customer->getUserName(), ENT_QUOTES); ?>" required>
                        </div>

                        <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="customer[password]"
                                required>
                        </div>

                        <h4 class="fw">Address</h4>
                        <div class="row g-3">

                            <input type="hidden" name="address[address_id]"
                                value="<?php echo $address->getAddressId() ?>">
                            <div class="col-md-12">
                                <label class="fw">Street Address</label>
                                <input type="text" name="address[street]" value="<?php echo $address->getStreet() ?>"
                                    class="form-control">
                            </div>
                            <div class="col-md-4">
                                <label class="fw">City</label>
                                <input type="text" name="address[city]" value="<?php echo $address->getCity() ?>"
                                    class="form-control">
                            </div>
                            <div class="col-md-4">
                                <label class="fw">Zip Code</label>
                                <input type="text" name="address[zip_code]" value="<?php echo $address->getZipCode() ?>"
                                    class="form-control">
                            </div>
                            <div class="col-md-4">
                                <label class="fw">State</label>
                                <input type="text" name="address[state]" value="<?php echo $address->getState() ?>"
                                    class="form-control">
                            </div>
                            <div class="col-md-6">
                                <label class="fw">Country</label>
                                <input type="text" name="address[country]" value="<?php echo $address->getCountry() ?>"
                                    class="form-control">
                            </div>
                        </div>



                        <div class="d-grid mt-3">
                            <button type="submit" class="btn btn-primary">Sign Up</button>
                        </div>


                    </form>
                </div>
                <div class="card-footer text-center">
                    <p class="mb-0">Already have an account? <a
                            href="<?php echo $this->getUrl('customer/account/login'); ?>">Log In</a></p>
                </div>
            </div>
        </div>
    </div>
</div>