<?php
$products = $this->listData();
// $editProduct = $this->editData();
?>

<div class="container py-5">
    <h4 class="mb-4 fw-bold text-dark">Product List</h4>
    <table class="table table-bordered">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>description</th>
                <th>sku</th>
                <th>Price</th>
                <th>stock_quantity</th>
                <th>category_id</th>
                <th>created_at</th>
                <th>updated_at</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($products as $product): ?>
                <tr>
                    <td><?php echo $product->getProductId(); ?></td>
                    <td><?php echo $product->getName(); ?></td>
                    <td><?php echo $product->getDescription(); ?></td>
                    <td><?php echo $product->getSku(); ?></td>
                    <td>₹<?php echo $product->getPrice(); ?></td>
                    <td><?php echo $product->getStockQuantity(); ?></td>
                    <td><?php echo $product->getCategoryId(); ?></td>
                    <td><?php echo $product->getCreatedAt(); ?></td>
                    <td><?php echo $product->getUpdatedAt(); ?></td>
                    <td>
                        <a href="<?php echo $this->getUrl('admin/product_index/new') . '/?product_id=' . $product->getProductId(); ?>"
                            class="btn btn-sm btn-warning">Edit</a>
                        <a href="delete/?id=<?php echo $product->getProductId(); ?>" class="btn btn-sm btn-danger"
                            onclick="return confirm('Are you sure?')">Delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>