<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="<?= $this->getUrl('') ?>">SHOP</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="<?= $this->getUrl('') ?>">Home</a>
                </li>
                <li class="nav-item">
                    <?php if (isset($_SESSION['login']) && $_SESSION['login'] == 1): ?>
                        <a class="nav-link" href="<?= $this->getUrl('admin/account/logout') ?>">Logout</a>
                    <?php else: ?>
                        <!-- <a class="nav-link" href="<?= $this->getUrl('admin/account/login') ?>">Login</a> -->
                    <?php endif; ?>
                </li>
                <li class="nav-item dropdown"></li>
                <!-- Sidebar Toggle Button -->
                <li class="nav-item">
                    <a class="nav-link" type="button" data-bs-toggle="offcanvas" data-bs-target="#categoryMenu">
                        Categories
                    </a>
                </li>
            </ul>
            <?php if (isset($_SESSION['login']) && $_SESSION['login'] == 1): ?>
                <a class="btn btn-outline-primary" href="<?= $this->getUrl('customer/dashboard/index') ?>">Dashboard</a>
            <?php endif; ?>

            <div class="nav-item ms-2">
                <a href="<?= $this->getUrl('checkout/cart/index') ?>" class="btn btn-outline-primary"><i
                        class="fas fa-shopping-cart"></i></a>
            </div>
            <div class="nav-item ms-2">

                <?php if (isset($_SESSION['customerLogin']) && $_SESSION['customerLogin'] == 1): ?>
                    <a class="btn btn-danger" href="<?= $this->getUrl('customer/account/logout') ?>">Logout</a>

                <?php else: ?>
                    <a class="btn btn-success" href="<?= $this->getUrl('customer/account/login') ?>">Login</a>
                    <a class="btn btn-success" href="<?= $this->getUrl('customer/account/registration') ?>">Signup</a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</nav>
<div class="offcanvas offcanvas-start" tabindex="-1" id="categoryMenu" aria-labelledby="categoryMenuLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="categoryMenuLabel">Categories</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>

</div>

