<head>
    <?php
    foreach ($this->getJs() as $js): ?>
        <script src="<?php echo Mage::getBaseUrl() . 'js/' . $js  ?>"></script>
    <?php endforeach; ?>

    <?php foreach ($this->getCss() as $css): ?>
        <link rel="stylesheet" href="<?php echo Mage::getBaseUrl() . 'css/' . $css  ?>">
    <?php endforeach; ?>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <!-- Font Awesome for Icons -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/js/all.min.js"></script>



</head>