<?php
$success = $this->getSuccess();
$error = $this->getError();
$warning = $this->getWarning();

?>
<?php if (!empty($success)) : ?>
    <div class="alert alert-success" role="alert">
        <?php echo $success; ?>
    </div>
<?php endif; ?>

<?php if (!empty($error)) : ?>
    <div class="alert alert-danger" role="alert">
        <?php echo $error; ?>
    </div>
<?php endif; ?>

<?php if (!empty($warning)) : ?>
    <div class="alert alert-warning" role="alert">
        <?php echo $warning; ?>
    </div>
<?php endif; ?>